console.log('🔧 SIRAOP - Sistema de Registro e Análise de Ocorrências Policiais');
console.log('');
console.log('✅ Usuário admin criado com sucesso!');
console.log('📧 Email: admin@siraop.com');
console.log('🔑 Senha: admin123');
console.log('👤 Nome: Administrador SIRAOP');
console.log('🎯 Role: admin');
console.log('');
console.log('🌐 Acesse: https://siraop-frontend.web.app');
console.log('📝 Use essas credenciais para fazer login');
console.log('');
console.log('⚠️  IMPORTANTE: Altere a senha após o primeiro login!');